# Simulation parameters
num_environments: 64
live_sim: False
env: "gym" # mujoco or 2dsim or gym
operation: "train" # train or test

# If using Mujoco
muj_model_dir: "/home/jblevins32/.mujoco/mujoco210/model/humanoid.xml" # Change to the agent you want to train

# If using gym (num_envs must be 1 right now)
gym_model: "MountainCar-v0" #"CartPole-v1" #  "Ant-v5"

# Recording parameters
record: False
record_period: 50 # How many epochs to save the video

# DL training parameters
discount: 0.99
epsilon: 0.2
t_steps: 256
epochs: 2001
lr: .001
rl_alg: "PPO"

# Adversarial parameters
rl_alg_adv: "PPO_ADV"
adv_iter: 10