# Simulation parameters
num_environments: 1
live_sim: False
env: "gym" # mujoco or 2dsim or gym
model_dir: "/home/jblevins32/.mujoco/mujoco210/model/humanoid.xml" # Change to the agent you want to train
operation: "train" # train or test

# DL training parameters
discount: 0.99
epsilon: 0.2
t_steps: 250
epochs: 250
lr: .001